version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
      - myapp:/myapp
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
  myapp:
