apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
        
    name: express-app
spec:
  ingressClassName: nginx
  rules:
    - host: app.express.com
      http:
        paths:
           - backend:
               service:
                 name: express-app
                 port:
                   number: 3000
             path: /
             pathType: Prefix
